version: '3.8'

services:
  mcp-server:
    build: 
      context: .
      dockerfile: Dockerfile
    image: git-context-mcp-forge:latest
    container_name: git-context-mcp-forge
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
      - FASTMCP_HOST=0.0.0.0
      - FASTMCP_PORT=8000
      - FASTMCP_TRANSPORT=sse
      - FASTMCP_DEBUG=true
      - TEMP_REPO_PATH=/tmp/repo_data
      - MAX_CONCURRENT_CLONES=3
    restart: unless-stopped
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge

volumes:
  chroma_db:
    driver: local